prompts: "Write a joke about {{topic}}"

providers: ollama:completion:llama3

tests:
  - vars:
      topic: bananas
    assert:
      - type: llm-rubric
        value: is a funny joke
        provider: ollama:completion:llama3